server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: buy
          uri: lb://buy
          predicates:
            - Path=/buy/**
        - id: datafetcher
          uri: lb://datafetcher
          predicates:
            - Path=/data/**